import type { Category, Skill } from "@/types/skill";

// Offline sample data so the app renders without Supabase credentials.
// Mirrors the real schema. Replace with live data once Supabase is wired up.

export const SAMPLE_CATEGORIES: Category[] = [
  { id: "cat_official", slug: "official", name: "Official", icon: "star" },
  { id: "cat_docs", slug: "docs", name: "Docs & Writing", icon: "document-text" },
  { id: "cat_code", slug: "code", name: "Code", icon: "code-slash" },
  { id: "cat_data", slug: "data", name: "Data", icon: "stats-chart" },
  { id: "cat_office", slug: "office", name: "Office", icon: "briefcase" },
  { id: "cat_design", slug: "design", name: "Design", icon: "color-palette" },
  { id: "cat_devops", slug: "devops", name: "DevOps", icon: "git-branch" },
  { id: "cat_research", slug: "research", name: "Research", icon: "search" },
  { id: "cat_misc", slug: "misc", name: "Misc", icon: "ellipsis-horizontal" },
];

const now = "2026-01-01T00:00:00.000Z";

function skill(partial: Partial<Skill> & Pick<Skill, "id" | "slug" | "name">): Skill {
  return {
    description: "",
    description_zh: null,
    category: "official",
    tags: [],
    use_cases: [],
    author: "anthropics",
    github_url: `https://github.com/anthropics/skills/tree/main/${partial.slug}`,
    skill_md_content: null,
    rank: 0,
    score: 0,
    featured: false,
    install_count: 0,
    skill_md_summary_zh: null,
    published_at: null,
    github_stars: null,
    created_at: now,
    updated_at: now,
    ...partial,
  };
}

export const SAMPLE_SKILLS: Skill[] = [
  skill({
    id: "sk_pdf",
    slug: "pdf",
    name: "PDF",
    description: "Read, extract and fill PDF files with high fidelity.",
    category: "office",
    tags: ["pdf", "documents", "extraction"],
    rank: 100,
    score: 98,
    install_count: 12400,
    featured: true,
    skill_md_content: `# PDF Skill\n\nRead, extract and fill PDF forms.\n\n## Usage\n\n- Extract text from any PDF.\n- Fill out PDF forms programmatically.\n- Merge / split documents.\n`,
  }),
  skill({
    id: "sk_docx",
    slug: "docx",
    name: "DOCX",
    description: "Create and edit Word documents with styles, tables and images.",
    category: "office",
    tags: ["word", "docx", "office"],
    rank: 95,
    score: 96,
    install_count: 9800,
    featured: true,
  }),
  skill({
    id: "sk_xlsx",
    slug: "xlsx",
    name: "XLSX",
    description: "Read, analyze and generate Excel spreadsheets with formulas.",
    category: "office",
    tags: ["excel", "spreadsheet", "office"],
    rank: 94,
    score: 95,
    install_count: 9500,
    featured: true,
  }),
  skill({
    id: "sk_pptx",
    slug: "pptx",
    name: "PPTX",
    description: "Build PowerPoint decks programmatically.",
    category: "office",
    tags: ["powerpoint", "slides", "office"],
    rank: 90,
    score: 94,
    install_count: 7200,
    featured: true,
  }),
  skill({
    id: "sk_canva",
    slug: "canva",
    name: "Canva Design",
    description: "Turn prompts into Canva designs via the Canva API.",
    category: "design",
    tags: ["canva", "design", "image"],
    rank: 78,
    score: 88,
    install_count: 4300,
    featured: true,
  }),
  skill({
    id: "sk_brand_guidelines",
    slug: "brand-guidelines",
    name: "Brand Guidelines",
    description: "Keep generated content consistent with your brand voice and palette.",
    category: "design",
    tags: ["brand", "writing", "style"],
    rank: 72,
    score: 86,
    install_count: 2100,
    featured: false,
  }),
  skill({
    id: "sk_artifacts_builder",
    slug: "artifacts-builder",
    name: "Artifacts Builder",
    description: "Scaffold React artifacts with sensible defaults for Claude.",
    category: "code",
    tags: ["react", "artifacts", "scaffold"],
    rank: 86,
    score: 92,
    install_count: 6100,
    featured: true,
  }),
  skill({
    id: "sk_webapp_testing",
    slug: "webapp-testing",
    name: "Webapp Testing",
    description: "Drive Playwright to test any webapp end-to-end.",
    category: "code",
    tags: ["playwright", "testing", "e2e"],
    rank: 80,
    score: 89,
    install_count: 5200,
    featured: true,
  }),
  skill({
    id: "sk_mcp_builder",
    slug: "mcp-builder",
    name: "MCP Builder",
    description: "Generate Model Context Protocol servers from a spec.",
    category: "devops",
    tags: ["mcp", "protocol", "server"],
    rank: 82,
    score: 90,
    install_count: 4800,
    featured: true,
  }),
  skill({
    id: "sk_slack_gif",
    slug: "slack-gif-creator",
    name: "Slack GIF Creator",
    description: "Make custom Slack emoji and reaction GIFs from prompts.",
    category: "design",
    tags: ["slack", "gif", "emoji"],
    rank: 60,
    score: 78,
    install_count: 1900,
    featured: false,
  }),
  skill({
    id: "sk_algorithmic_art",
    slug: "algorithmic-art",
    name: "Algorithmic Art",
    description: "Generate generative art with p5.js and svg output.",
    category: "design",
    tags: ["art", "creative", "svg"],
    rank: 58,
    score: 76,
    install_count: 1500,
    featured: false,
  }),
  skill({
    id: "sk_internal_comms",
    slug: "internal-comms",
    name: "Internal Comms",
    description: "Draft internal announcements, changelogs and standup notes.",
    category: "docs",
    tags: ["writing", "comms", "standup"],
    rank: 66,
    score: 82,
    install_count: 2300,
    featured: false,
  }),
  skill({
    id: "sk_financial_analysis",
    slug: "financial-analysis",
    name: "Financial Analysis",
    description: "Parse 10-Ks, run ratios and produce executive summaries.",
    category: "data",
    tags: ["finance", "analysis", "reports"],
    rank: 84,
    score: 91,
    install_count: 3700,
    featured: true,
  }),
  skill({
    id: "sk_research_writer",
    slug: "research-writer",
    name: "Research Writer",
    description: "Citation-heavy long-form research documents.",
    category: "research",
    tags: ["research", "citations", "writing"],
    rank: 74,
    score: 87,
    install_count: 2800,
    featured: true,
  }),
  skill({
    id: "sk_data_analyst",
    slug: "data-analyst",
    name: "Data Analyst",
    description: "Clean, query and visualize tabular data with pandas.",
    category: "data",
    tags: ["pandas", "analysis", "viz"],
    rank: 88,
    score: 93,
    install_count: 6400,
    featured: true,
  }),
  skill({
    id: "sk_skill_creator",
    slug: "skill-creator",
    name: "Skill Creator",
    description: "Meta-skill that helps you author new SKILL.md files.",
    category: "official",
    tags: ["meta", "authoring"],
    rank: 99,
    score: 97,
    install_count: 8800,
    featured: true,
  }),
];
