// Local Chinese summaries for skills whose source description_zh is missing.
// Keep this bundle as a display fallback; the original source remains untouched.
export const DESCRIPTION_ZH: Record<string, string> = {
  "agy-auto": "为 Antigravity CLI 配置分层权限策略，在无需跳过全部权限检查的情况下安全运行自动化任务。",
  "agy-delegate": "仅在用户明确要求时，将编码任务交给 Google Antigravity CLI 执行，并保留审查与集成责任。",
  "aider-delegate": "仅在用户明确要求时，将编码任务交给 Aider CLI 执行，并由主流程负责审查和合并。",
  "api-rate-limit-handler": "为 API 实现有边界且可幂等的限流、退避和重试机制，妥善处理 429 与临时 5xx 错误。",
  "api-security": "在授权范围内评估 REST、GraphQL、WebSocket 和 SOAP API，检查认证授权缺陷、限流与常见越权风险。",
  "apk-reverse": "分析 Android APK，涵盖解包、Java 反编译、smali 修改、重签名、Frida 动态调试和原生库检查。",
  "attack-chain": "在授权项目中规划多阶段攻击路径，覆盖侦察、初始访问、权限提升、横向移动和结果报告。",
  "babysit-pr": "持续跟进拉取请求的机器人审查轮次，逐项核实、修复、回复并解决评审意见。",
  "binary-diff": "比较不同版本的二进制文件，恢复符号和函数名称，并在软件更新后迁移已有分析标注。",
  "break-ai-fix-loops": "用稳定故障指纹、尝试次数上限、真实路径验证和回滚检查，终止无效的 AI 修复循环。",
  "browser-extension-reverse": "在授权范围内逆向分析浏览器扩展，检查清单、后台任务、内容脚本及凭据或数据暴露风险。",
  "case-review": "对逆向工程或安全评估案例进行质量审查，核对范围、证据链、任务覆盖、时间线和文件校验值。",
  "check-identity-pack": "按澳大利亚身份核验要求检查一组证件材料，列出缺失项并评估材料是否满足开户核验条件。",
  "claude-delegate": "仅在用户明确要求时，将编码任务交给指定的 Claude Code CLI 或会话，并由主流程负责审查与集成。",
  "client-secret-exposure-audit": "审计已部署网页是否向浏览器暴露密钥，检查前端代码、HTML、公开配置文件及跨域响应设置。",
  "cline-delegate": "仅在用户明确要求时，将编码任务交给 Cline CLI 执行，并由主流程负责审查和集成。",
  "cloud-k8s": "在授权范围内评估云、容器和 Kubernetes 安全，检查元数据 SSRF、IAM 配置、容器逃逸及集群权限。",
  "code-audit": "开展授权的源码安全审查，使用 Semgrep、CodeQL 等方法定位危险调用并验证修复效果。",
  "codex-delegate": "仅在用户明确要求时，将编码任务交给 OpenAI Codex CLI 执行，并由主流程负责审查和集成。",
  "commandcode-delegate": "仅在用户明确要求时，将编码任务交给 Command Code CLI 执行，并由主流程负责审查和集成。",
  "copilot-delegate": "仅在用户明确要求时，将编码任务交给 GitHub Copilot CLI 执行，并由主流程负责审查和集成。",
  "cursor-delegate": "仅在用户明确要求时，将编码任务交给 Cursor Agent CLI 执行，并由主流程负责审查和集成。",
  "database-security": "在授权范围内评估 PostgreSQL、MySQL、MSSQL、MongoDB 和 Redis，检查暴露、权限缺口及错误配置。",
  "debate-review": "通过双模型辩论审查代码变更，可审查 GitHub、GitLab、Azure DevOps 请求或本地工作区并输出结论。",
  "delegate-setup": "配置已安装编码工具之间获准使用的委派通道；只有获得明确批准后才写入全局或项目配置。",
  "detect-ai-text": "根据语言特征估计文本是否由 AI 生成，并在证据不足时明确保留判断，不把结果当作定论。",
  "diagram-generator": "根据自然语言、笔记、代码或架构生成并校验流程图、泳道图、攻击路径图和数据流图等图表。",
  "digital-forensics": "在授权事件响应中分析内存、磁盘时间线、网络包和系统痕迹，并保全调查证据。",
  "docs-generator": "把已完成的技术分析整理成有证据支撑的逆向工程报告、渗透测试报告、CTF 复盘和分析文档。",
  "docx": "创建、读取、编辑和转换 Word 文档，支持模板、修订、批注、报告及排版完善的文档交付。",
  "dotnet-reverse": "逆向分析 .NET 与 C# 程序，涵盖托管 PE、调试反编译、去混淆、IL 修改和 NativeAOT。",
  "dsl-vm-reverse": "逆向分析基于 JavaScript 的自定义 DSL 或虚拟机，恢复操作码分派逻辑、指令表与运行语义。",
  "edr-bypass-re": "研究 EDR 内部机制和绕过技术，包括用户态钩子、ETW、AMSI 与系统调用；仅限授权实验室。",
  "email-issue-fixer": "修正邮件中的小错误并保留作者语气；按要求清理链接跟踪参数，同时返回修改稿和变更清单。",
  "email-security": "在授权范围内审查邮件安全，分析钓鱼邮件、SPF/DKIM/DMARC 身份验证、商务邮件欺诈和令牌滥用。",
  "entropy-box": "将具身 AI 的限定需求整理为有依据的工作流程，支持方案咨询、搜索、资料查找和证据核验。",
  "extract-document-data": "从文件中提取有来源依据的结构化字段，为结果标注页码；缺失信息会留空而不是猜测补齐。",
  "falsify": "用假设、反证尝试和证据校验处理复杂或高风险问题，降低凭直觉猜测造成错误结论的概率。",
  "famulor-skill": "通过托管 MCP 管理 Famulor 助手、通信记录、营销活动、知识库、自动化、电话和工作区设置。",
  "find-matching-tenders": "查找与企业业务匹配的澳大利亚和新西兰政府招标，按契合度排序并分析优势与差距。",
  "firmware-pentest": "按 OWASP FSTM 流程开展授权固件测试，覆盖提取、自动分析、模拟运行、模糊测试和实验室验证。",
  "ghidra-reverse": "使用 Ghidra 对程序进行开源逆向分析，支持反编译、交叉引用、脚本及可选 MCP 工作流。",
  "glasser": "在当前环境缺少合适集成时，通过统一命令行查询、检查并调用第三方数据 API。",
  "go-rust-reverse": "逆向分析剥离符号的 Go 与 Rust 二进制文件，恢复运行时信息并还原关键数据结构和逻辑。",
  "graceful-shutdown": "为服务器和后台任务实现平滑关闭，排空连接、完成进行中工作、释放资源并响应终止信号。",
  "grok-delegate": "仅在用户明确要求时，将编码任务交给 Grok Build CLI 执行，并由主流程负责审查和集成。",
  "hardware-security": "在授权范围内研究硬件和嵌入式接口安全，包括 UART/JTAG 检查、安全启动和离线固件分析。",
  "ida-reverse": "使用 IDA Pro 逆向分析二进制程序，支持反编译、反汇编、数据流追踪、交叉引用和自动化操作。",
  "identity-federation": "在授权范围内评估联合身份系统，检查 SAML、OIDC、OAuth2、单点登录配置和令牌混淆风险。",
  "instructree": "在修改代码前，梳理并检查仓库范围内的编码代理指令，帮助识别规则冲突和适用范围。",
  "js-reverse": "逆向分析前端 JavaScript，定位签名逻辑、加密请求参数并在本地复现运行行为以验证结果。",
  "kimi-delegate": "仅在用户明确要求时，将编码任务交给 Kimi Code CLI 执行，并由主流程负责审查和集成。",
  "laravel-development-workflow": "通过根因诊断、项目原生实现、回归覆盖和风险验证，开发或修复现有 Laravel 应用。",
  "llm-security": "在授权范围内评估大语言模型应用和智能体安全，检查提示注入、工具滥用、RAG 泄漏与越权问题。",
  "macos-reverse": "在授权范围内逆向分析 macOS 和 Mach-O 程序，检查签名、恢复 Objective-C/Swift 逻辑及恶意软件行为。",
  "malware-analysis": "结合静态、动态和行为分析调查疑似恶意软件，提取 IOC 并编写 YARA/Sigma 规则或运行沙箱。",
  "marketplace-rbac-audit": "审计多角色交易平台的授权规则，核对角色、资源归属、租户边界和订单状态转换权限。",
  "md2video-audio": "将 Markdown 文档转换为带旁白的 MP4 视频，并同步安排画面内容和语音讲解。",
  "mobile-reverse": "在授权范围内逆向分析和测试 Android/iOS 应用，涵盖安装包分析、运行时调试及 OWASP MASTG 检查。",
  "muapi-media": "通过 MuAPI 异步媒体接口生成图片和视频，并妥善处理密钥、任务轮询和结果下载。",
  "omp-delegate": "仅在用户明确要求时，将编码任务交给 Oh My Pi CLI 执行，并由主流程负责审查和集成。",
  "opencode-delegate": "仅在用户明确要求时，将编码任务交给 OpenCode CLI 执行，并由主流程负责审查和集成。",
  "orca-replay": "根据运行记录回答过去的智能体执行情况，并支持重放或分叉历史运行以复现问题。",
  "ot-ics": "在授权范围内评估工业控制系统安全，检查区域隔离、PLC/SCADA 暴露和工业协议，并优先采用被动分析。",
  "parallel-search-mcp": "通过 Parallel Search MCP 搜索公开网页并核验来源，适用于用户选定该工具获取最新信息时。",
  "patch-diff-exploit": "分析供应商补丁并比较二进制版本，定位漏洞修复位置，为授权研究构建 N-day 概念验证。",
  "pdf": "读取、创建和处理 PDF 文件，支持文本或表格提取、合并拆分、旋转、加水印、表单填写和扫描件 OCR。",
  "pentest-tools": "通过结构化流程调用 Nmap、Nuclei、SQLMap、FFUF、Hashcat 等二十余种渗透测试工具。",
  "pi-delegate": "仅在用户明确要求时，将编码任务交给 Pi 编码代理 CLI 执行，并由主流程负责审查和集成。",
  "poka-yoke": "通过设计让错误操作无法发生或能及时显现，为代码、配置和工作流程加入防错措施。",
  "pptx": "创建、读取和编辑 PowerPoint 演示文稿，支持模板、版式、备注、修复、重排和内容清理。",
  "production-runtime-certification": "基于源码、持续集成、数据库迁移、运行健康和关键路由的最新证据，核验服务上线状态。",
  "project-state-governor": "跨会话、分支和评审维护有证据支撑的项目状态，避免把推测误写成已确认需求。",
  "protocol-reverse": "在授权范围内逆向分析自定义二进制协议，恢复 Protobuf/gRPC 结构、WebSocket 帧和网络包语义。",
  "pwn-chain": "在 CTF 或授权目标中串联逆向分析与漏洞利用，覆盖栈、堆、内核和 ROP 利用链调试。",
  "qoder-delegate": "仅在用户明确要求时，将编码任务交给 Qoder CLI 执行，并由主流程负责审查和集成。",
  "radare2": "使用 radare2 命令行工具完成二进制侦察、反汇编、函数定位、导出和轻量级补丁操作。",
  "radio-sdr": "在屏蔽实验室和合法频段外的合规边界内开展授权射频安全研究、信号识别与协议分析。",
  "reverse-browser-automation": "自动化浏览器和 Windows 桌面应用，收集逆向分析证据、执行界面流程并观察网络交互。",
  "reverse-engineering": "为编译、混淆、加壳或虚拟化目标提供通用逆向方法，涵盖 GDB、Frida、angr、Unicorn 与 Qiling。",
  "sandbase-mcp": "通过 SandBase 本地 MCP 桥接发现、检查并调用两千余种 AI 模型和 API，查看接口规格与成本。",
  "screen-adverse-media": "筛查个人或机构的负面媒体、政要及制裁风险；结果用于复核而非定罪，并支持持续监测。",
  "skill-porter": "预览保守的工具名称翻译，并复制完整本地技能包，供人工适配到 Google Antigravity。",
  "skill-security-audit": "安装前审计 Agent Skill、MCP 服务或桌面扩展，追踪代码、依赖、权限、凭据和数据流向。",
  "slideops": "从代码仓库生成带引用的 HTML 幻灯片，并检测内容是否过期；引用记录文件、行号和哈希。",
  "spec-driven-loop": "在中大型开发前固定产品需求、技术设计和验收标准，再依据差异、测试和证据评估交付。",
  "src-hunter": "按接收、侦察、枚举、排查和报告五阶段开展授权漏洞赏金或 SRC 安全研究。",
  "supply-chain-security": "评估软件供应链安全，检查 SBOM、依赖漏洞、CI/CD、容器镜像、构建完整性和漏洞可达性。",
  "thick-client": "在授权范围内测试桌面厚客户端安全，检查本地存储、更新通道、进程通信、流量和信任边界。",
  "threat-hunting": "开展蓝队威胁狩猎，使用 Sigma/YARA 编写检测规则、设计 SIEM 查询并验证告警有效性。",
  "threat-intelligence": "基于公开来源补充 IOC、攻击活动、仿冒诈骗和威胁组织信息，并明确情报收集边界。",
  "unsloth-finetuning": "使用 Unsloth Core 在单张消费级 GPU 上微调大语言模型，涵盖显存规划、LoRA、DPO 和 GGUF 导出。",
  "upstash-ratelimit": "使用 @upstash/ratelimit 和 Upstash Redis，为 API 路由、中间件及边缘函数配置多种限流策略。",
  "upstash-redis": "通过 @upstash/redis HTTP 客户端在无服务器和边缘环境中实现缓存、会话、计数器及 Redis 数据结构。",
  "verify-citations": "核验文档、报告或文章中的引用是否对应真实来源，检查事实、参考文献和研究证据。",
  "verify-document": "在依赖 PDF 或图片文件前检查篡改或伪造迹象，适用于工资单、发票、银行账单和合同等材料。",
  "vibe-delegate": "仅在用户明确要求时，将编码任务交给 Mistral Vibe CLI 执行，并由主流程负责审查和集成。",
  "warp-delegate": "仅在用户明确要求时，将编码任务交给 Warp Agent CLI 执行，并由主流程负责审查和集成。",
  "wifi-wireless": "在授权无线网络评估中检查 Wi-Fi 捕获、WPA 握手和恶意接入点；仅限实验环境进行干扰测试。",
  "windows-ad": "在授权环境中评估 Active Directory 安全，检查 Kerberos、AD CS、BloodHound 路径和 NTLM 中继风险。",
  "xlsx": "读取、创建和编辑 Excel 或 CSV 文件，支持公式、格式、图表、数据清理和表格结构整理。",
  "zcode-delegate": "仅在用户明确要求时，将编码任务交给 Z.AI ZCode CLI 执行，并由主流程负责审查和集成。",
};

export function skillDescriptionZh(skill: { slug: string; description_zh: string | null }): string {
  return skill.description_zh?.trim() || DESCRIPTION_ZH[skill.slug] || "中文简介待补充";
}
